<a href="https://colab.research.google.com/github/alaa126458/Data-analysis/blob/main/Employee_Salaries_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("Employee_Salaries.csv")
df.head()

,Department,Department_Name,Division,Gender,Base_Salary,Overtime_Pay,Longevity_Pay,Grade
0,ABS,Alcohol Beverage Services,ABS 85 Administration,M,175873.000,0.00,0.0,M2
1,ABS,Alcohol Beverage Services,ABS 85 Administration,M,145613.360,0.00,0.0,M3
2,ABS,Alcohol Beverage Services,ABS 85 Administration,F,136970.000,0.00,0.0,M3
3,ABS,Alcohol Beverage Services,ABS 85 Administrative Services,F,89432.694,0.00,2490.0,21
4,ABS,Alcohol Beverage Services,ABS 85 Administrative Services,F,78947.000,456.68,6257.7,16

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10291 entries, 0 to 10290
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Department       10291 non-null  object
 1   Department_Name  10291 non-null  object
 2   Division         10291 non-null  object
 3   Gender           10291 non-null  object
 4   Base_Salary      10291 non-null  float64
 5   Overtime_Pay     10291 non-null  float64
 6   Longevity_Pay    10291 non-null  float64
 7   Grade            10258 non-null  object
dtypes: float64(3), object(5)
memory usage: 643.3+ KB

In [6]:
df.describe()

         Base_Salary   Overtime_Pay  Longevity_Pay
count   10291.000000   10291.000000   10291.000000
mean    90312.165744    8081.288954    1533.882816
std     31240.842929   16491.833017    3209.041070
min     11147.240000       0.000000       0.000000
25%     70023.000000       0.000000       0.000000
50%     87328.000000     258.420000       0.000000
75%    108084.000000    9190.970000    1225.680000
max    292000.000000  227428.990000   20279.460000

In [10]:
#What is the average base salary?
df['Base_Salary'].mean()

90312.16574420367

In [11]:
#what is the highest amount of overtime pay?
df['Overtime_Pay'].max()

227428.99

In [19]:
df['BasePay_benefit']=df['Base_Salary']+df['Overtime_Pay']
df

,Department,Department_Name,Division,Gender,Base_Salary,Overtime_Pay,Longevity_Pay,Grade,BasePay_benefit
0,ABS,Alcohol Beverage Services,ABS 85 Administration,M,175873.0000,0.00,0.00,M2,175873.0000
1,ABS,Alcohol Beverage Services,ABS 85 Administration,M,145613.3600,0.00,0.00,M3,145613.3600
2,ABS,Alcohol Beverage Services,ABS 85 Administration,F,136970.0000,0.00,0.00,M3,136970.0000
3,ABS,Alcohol Beverage Services,ABS 85 Administrative Services,F,89432.6940,0.00,2490.00,21,89432.6940
4,ABS,Alcohol Beverage Services,ABS 85 Administrative Services,F,78947.0000,456.68,6257.70,16,79403.6800
...,...,...,...,...,...,...,...,...,...
10286,TBS,Department of Technology and Enterprise Busine...,TBS 34 OSP Low Code Governance and Administration,M,134500.0000,0.00,0.00,N28,134500.0000
10287,ZAH,Office of Zoning and Administrative Hearings,ZAH 05 Director,F,215032.1000,0.00,0.00,NaN,215032.1000
10288,ZAH,Office of Zoning and Administrative Hearings,ZAH 05 Office of Zoning and Administrative Hea...,F,84365.5529,0.00,0.00,N18,84365.5529
10289,ZAH,Office of Zoning and Administrative Hearings,ZAH 05 Zoning and Administrative Hearings,F,98228.0000,0.00,1596.27,N21,98228.0000
10290,ZAH,Office of Zoning and Administrative Hearings,ZAH 05 Zoning and Administrative Hearings,F,177976.3100,0.00,0.00,N35,177976.3100

In [26]:
#what is the name of department name make the highest (benefits)?
df[df['BasePay_benefit']==df['BasePay_benefit'].max()]['Department_Name']

4455    Fire and Rescue Services
Name: Department_Name, dtype: object

In [23]:
#what is name of department name make the lowest(benefits)?
df[df['BasePay_benefit']==df['BasePay_benefit'].min()]['Department_Name']

7579    Office of Agriculture
Name: Department_Name, dtype: object

In [33]:
#what is the average base pay of all department name for all gender?
df.groupby('Gender')['Base_Salary'].mean()

Gender
F    87497.502790
M    92382.929752
Name: Base_Salary, dtype: float64

In [35]:
#how many department name are there?
df['Department_Name'].nunique()

42

In [37]:
#what are the top 5 Common department name?
df['Department_Name'].value_counts().head()

Department_Name
Department of Health and Human Services    1877
Department of Police                       1794
Fire and Rescue Services                   1440
Department of Transportation               1289
Correction and Rehabilitation               513
Name: count, dtype: int64